name: lint and tests check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        run: make lint
      
      - name: test
        run: make test